{{- if not .Values.pvc.config.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.config.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.config.storage | quote }}
{{- end }}
{{- if not .Values.pvc.media.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-media
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.media.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.media.storage | quote }}
{{- end }}
{{- if not .Values.pvc.cache.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.cache.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.cache.storage | quote }}
{{- end }}
