apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-appservice-irc.fullname" . }}
  labels:
    {{- include "matrix-appservice-irc.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- fromYaml .Values.config | toYaml | nindent 4 }}
  appservice-registration-irc.yaml: |
    {{- fromYaml .Values.registration | toYaml | nindent 4 }}
  passkey.pem: |
    {{- .Values.passkey | nindent 4 }}
