apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-appservice-irc.fullname" . }}-appservice-nocollide
  labels:
    {{- include "matrix-appservice-irc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: appservice
      protocol: TCP
      name: appservice
  selector:
    {{- include "matrix-appservice-irc.selectorLabels" . | nindent 4 }}
