---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timetagger.fullname" . }}
  labels:
    {{- include "timetagger.labels" . | nindent 4 }}
stringData:
  {{- $creds := "" -}}
  {{- $first := true }}
  {{- range $username, $password := .Values.users }}
    {{- if $first }}
        {{- $creds = printf "%s%s" $creds (htpasswd $username $password) }}
    {{- else }}
        {{- $creds = printf "%s,%s" $creds (htpasswd $username $password) }}
    {{- end }}
    {{- $first = false }}
  {{- end }}
  TIMETAGGER_CREDENTIALS: "{{ $creds }}"
  {{- list .Values.config "TIMETAGGER" | include "recurseFlattenMap" | nindent 2 }}
