# Default values for esphome.
# This is a YAML-formatted file.
image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

revisionHistoryLimit: 5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

pvc:
  config:
    existingClaim: false
    storageClassName: ""
    storage: "1Gi"
  storage:
    existingClaim: false
    storageClassName: ""
    storage: "5Gi"
  database:
    existingClaim: false
    storageClassName: ""
    storage: "5Gi"


mainConfig:
  http:
    server_port: 443
    ssl_certificate: /media/certificates/tls.crt
    ssl_key: /media/certificates/tls.key
    use_x_forwarded_for: true
  recorder:
    db_url: sqlite:////media/database/hass-db.sqlite
config:
  packages: ""

cert:
  dnsNames: []
  issuerName: ""
