# Default values for mautrix-signal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: dock.mau.dev/mautrix/signal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

revisionHistoryLimit: 5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1337
  runAsGroup: 1337

service:
  type: ClusterIP
  port: 29328

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Mautrix-signal configuration must be in the config key here:
# however it is recomended to keep it in a different file and
# use --set-file config=config.yaml when invoking helm.
# This allows diffing with the example configuration to update it.
config: {}

signald:
  image:
    repository: registry.gitlab.com/signald/signald
    pullPolicy: IfNotPresent
    tag: "0.23.0"
  config: {}
#    database: ""
  pvc:
    storageClassName: ""
    existingClaim: false
    storage: 5Gi
