apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rust-synapse-compress-state.fullname" . }}
  labels:
    {{- include "rust-synapse-compress-state.labels" . | nindent 4 }}
# The cronjob spec.
spec:
    schedule: {{ .Values.schedule }}
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 3600
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    jobTemplate:
      # The job spec
      spec:
        backoffLimit: 1
        # The pod template.
        template:
          metadata:
            {{- with .Values.podAnnotations }}
            annotations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            labels:
              {{- include "rust-synapse-compress-state.selectorLabels" . | nindent 14 }}
          spec:
            {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            securityContext:
              {{- toYaml .Values.podSecurityContext | nindent 14 }}
            restartPolicy: Never
            containers:
              - name: {{ .Chart.Name }}
                securityContext:
                  {{- toYaml .Values.securityContext | nindent 18 }}
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                resources:
                  {{- toYaml .Values.resources | nindent 18 }}
                command:
                  - /usr/local/bin/synapse_auto_compressor
                args:
                  - -p
                  - "$(POSTGRES_CONNECTION_STRING)"
                  - -c
                  - {{ .Values.chunkSize | quote }}
                  - -n
                  - {{ .Values.numChunks | quote }}
                env:
                  - name: POSTGRES_CONNECTION_STRING
                    valueFrom:
                      secretKeyRef:
                        name: {{ include "rust-synapse-compress-state.fullname" . }}
                        key: postgres-connection-string
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
