---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rust-synapse-compress-state.fullname" . }}
  labels:
    {{- include "rust-synapse-compress-state.labels" . | nindent 4 }}
stringData:
  postgres-connection-string: {{ .Values.postgresConnectionString }}
