apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt.fullname" . }}-mqtt-mosquittoconf
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
data:
    mosquitto.conf: |
        listener 1883
        allow_anonymous true
