apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt.fullname" . }}-mqtt
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      hass.kube.a09.uk/automationService: mqtt
      {{- include "mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mqtt/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        hass.kube.a09.uk/automationService: mqtt
        {{- include "mqtt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}-mqtt
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mqtt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mosquittoconf
              mountPath: "mosquitto/config"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: mosquittoconf
          configMap:
            name: {{ include "mqtt.fullname" . }}-mqtt-mosquittoconf
            items:
                - key: "mosquitto.conf"
                  path: "mosquitto.conf"
