apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt.fullname" . }}-mqtt
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    hass.kube.a09.uk/automationService: mqtt
    {{- include "mqtt.selectorLabels" . | nindent 4 }}
