---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- fromYaml .Values.config | toYaml | nindent 4 }}
  registration.yaml: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-signal.fullname" . }}-signald-config
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{- list .Values.signald.config "SIGNALD" | include "recurseFlattenMap" | nindent 4 }}
