{{- if .Values.cert.dnsNames }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  secretName: {{ include "homeassistant.fullname" . }}-tls-cert-secret
  secretTemplate:
    labels:
      {{- include "homeassistant.labels" . | nindent 6 }}
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    {{- range .Values.cert.dnsNames }}
    - {{ . | quote}}
    {{- end }}
  issuerRef:
    name: {{ .Values.cert.issuerName }}
    kind: ClusterIssuer
{{- end }}
