apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-configuration
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    homeassistant:
      {{- range $key, $value := .Values.config.homeassistant }}
      {{ printf "%s: %s" $key ($value | quote) }}
      {{- end }}
      packages: !include_dir_named /media/packages
    default_config:
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    {{ .Values.mainConfig | toYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-packages
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  {{- range $key, $value := fromYaml .Values.config.packages }}
  "{{ $key }}": |
    {{- $value | toYaml | nindent 4 }}
  {{- end }}
