---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      hass.kube.a09.uk/automationService: esphome
      {{- include "esphome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        hass.kube.a09.uk/automationService: esphome
        {{- include "esphome.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            {{- if not .Values.pvc.config.existingClaim }}
            claimName: {{ include "esphome.fullname" . }}-config
            {{- else }}
            claimName: {{ .Values.pvc.config.existingClaim }}
            {{- end }}
        - name: cache
          persistentVolumeClaim:
            {{- if not .Values.pvc.cache.existingClaim }}
            claimName: {{ include "esphome.fullname" . }}-cache
            {{- else }}
            claimName: {{ .Values.pvc.config.existingClaim }}
            {{- end }}
