{{- if not .Values.pvc.config.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "esphome.fullname" . }}-config
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.config.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.config.storage | quote }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "esphome.fullname" . }}-store
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.store.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.store.storage | quote }}
