# Default values for mautrix-instagram.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: dock.mau.dev/mautrix/instagram
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1337
  runAsGroup: 1337
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 29330

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Mautrix-instagram configuration must be in the config key here:
# however it is recomended to keep it in a different file and
# use --set-file config=config.yaml when invoking helm.
# This allows diffing with the example configuration to update it.
config: {}
