---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "node-red.fullname" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.pvc.capacity }}
  storageClassName: {{ .Values.pcv.storageClassName }}
