---
when:
  path: "charts/mqtt/**"
  branch: main
steps:
  package:
    image: "docker.io/alpine/helm:latest"
    secrets: [helm_user, helm_password, helm_repo]
    commands:
      - helm plugin install https://github.com/chartmuseum/helm-push
      - helm repo add therepo $HELM_REPO --username $HELM_USER --password $HELM_PASSWORD
      - helm cm-push charts/mqtt therepo
